### ISSUE TITLE
broken pypi link

### ISSUE THREAD

**Issue by tovmeod** [vtemian/django-server-timing#1]
The [pypi page](https://pypi.python.org/pypi/django-server-timing) links to http://github.com/vtemian/django-silver-timing which doesn't exist

**Comment by samuelcolvin** [comment]
Just about to report the same thing.

https://github.com/vtemian/django-server-timing/blob/acc2a422b107d7ad48b84e66a888759f236b8735/setup.py#L11

**Comment by vtemian** [comment]
Thanks! Solved in https://github.com/vtemian/django-server-timing/commit/467779f101444bc82819741de0b1c756b13fbb7d
